[tool.poetry]
name = "library"
version = "0.1.0"
description = ""
authors = ["Jorge <jorgesilva.ti@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.0"
uvicorn = "^0.21.1"
pydantic = "^1.10.6"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
httpx = "^0.23.3"
flake8 = "^6.0.0"
black = "^23.1.0"
isort = "^5.12.0"
pydocstyle = "^6.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
